# Change these first
owner: entropyhub # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Lexico.com
    url: https://www.lexico.com
  - name: Lexico Landing Page
    url: https://www.lexico.com/about
  - name: Lexico Category Page
    url: https://www.lexico.com/grammar
  - name: Lexico Sitemap
    url: https://www.lexico.com/sitemap
  - name: Lexico English Definition
    url: https://www.lexico.com/definition/bank
  - name: Lexico Spanish Definition
    url: https://www.lexico.com/es/definicion/agua
  - name: Staging Lexico.com
    url: https://staging.lexico.com
    headers:
      - "Authorization: Basic $STAGING_ACCESS"
  - name: Staging Lexico.com Spanish Definition
    url: https://staging.lexico.com/es/definicion/agua
    headers:
      - "Authorization: Basic $STAGING_ACCESS"
  - name: Staging Lexico.com/es/definicion Broken Page
    url: https://staging.lexico.com/es/definicion
    headers:
      - "Authorization: Basic $STAGING_ACCESS"


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Lexico Uptime Monitor
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
