# Change these first
owner: entropyhub # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Lexico.com
    url: https://www.lexico.com
  - name: Lexico Landing Page
    url: https://www.lexico.com/about
  - name: Lexico Category Page
    url: https://www.lexico.com/grammar
  - name: Lexico Sitemap
    url: https://www.lexico.com/sitemap
  - name: Lexico English Definition
    url: https://www.lexico.com/definition/bank
  - name: Lexico Spanish Definition
    url: https://www.lexico.com/es/definicion/agua
  - name: Staging Lexico.com
    url: https://staging.lexico.com
    headers:
      - "Authorization: Basic $STAGING_ACCESS"
  - name: Staging Lexico.com Spanish Definition
    url: https://staging.lexico.com/es/definicion/agua
    headers:
      - "Authorization: Basic $STAGING_ACCESS"
  - name: Staging Lexico.com/es/definicion Broken Page
    url: https://staging.lexico.com/es/definicion
    headers:
      - "Authorization: Basic $STAGING_ACCESS"
  - name: Lexico GSC Coverage m/en/definition/word%
    url: https://www.lexico.com/en/definition/word%
  - name: Lexico GSC Coverage m/definition/training <042D><0442><043E>
    url: https://www.lexico.com/definition/training <042D><0442><043E>
  - name: Lexico GSC Coverage m/definition/추락시키다
    url: https://www.lexico.com/definition/추락시키다
  - name: Lexico GSC Coverage m/definition/word%
    url: https://www.lexico.com/definition/word%
  - name: Lexico GSC Coverage m/definition/post-truthhttps:/en.oxforddictionaries.com/definition/post-truth</a></p><p>[2]</a>
    url: https://www.lexico.com/definition/post-truthhttps:/en.oxforddictionaries.com/definition/post-truth</a></p><p>[2]</a>
  - name: Lexico GSC Coverage m/definition/whirled
    url: https://www.lexico.com/definition/whirled
  - name: Lexico GSC Coverage m/definition/cowchip
    url: https://www.lexico.com/definition/cowchip
  - name: Lexico GSC Coverage m/definition/millihertz
    url: https://www.lexico.com/definition/millihertz
  - name: Lexico GSC Coverage m/definition/rubberneck wagon
    url: https://www.lexico.com/definition/rubberneck wagon
  - name: Lexico GSC Coverage m/definition/바다가재
    url: https://www.lexico.com/definition/바다가재
  - name: Lexico GSC Coverage m/definition/맞지 않는
    url: https://www.lexico.com/definition/맞지 않는
  - name: Lexico GSC Coverage m/definition/dodad
    url: https://www.lexico.com/definition/dodad
  - name: Lexico GSC Coverage m/synonyms/face_airing
    url: https://www.lexico.com/synonyms/face_airing
  - name: Lexico GSC Coverage m/synonyms/monochorionic
    url: https://www.lexico.com/synonyms/monochorionic
  - name: Lexico GSC Coverage m/definition/CIWS
    url: https://www.lexico.com/definition/CIWS
  - name: Lexico GSC Coverage m/definition/긔틀
    url: https://www.lexico.com/definition/긔틀
  - name: Lexico GSC Coverage m/definition/대아
    url: https://www.lexico.com/definition/대아
  - name: Lexico GSC Coverage m/definition/송진
    url: https://www.lexico.com/definition/송진
  - name: Lexico GSC Coverage m/en/definition/Ouachita_River
    url: https://www.lexico.com/en/definition/Ouachita_River
  - name: Lexico GSC Coverage m/definition/gerunds
    url: https://www.lexico.com/definition/gerunds
  - name: Lexico GSC Coverage m/definition/구슬옥
    url: https://www.lexico.com/definition/구슬옥
  - name: Lexico GSC Coverage m/definition/固定作用
    url: https://www.lexico.com/definition/固定作用
  - name: Lexico GSC Coverage m/definition/skewers
    url: https://www.lexico.com/definition/skewers
  - name: Lexico GSC Coverage m/definition/stay of execution
    url: https://www.lexico.com/definition/stay of execution
  - name: Lexico GSC Coverage m/definition/미자
    url: https://www.lexico.com/definition/미자
  - name: Lexico GSC Coverage m/definition/존립
    url: https://www.lexico.com/definition/존립
  - name: Lexico GSC Coverage m/definition/쉐도우
    url: https://www.lexico.com/definition/쉐도우
  - name: Lexico GSC Coverage m/definition/명명법
    url: https://www.lexico.com/definition/명명법
  - name: Lexico GSC Coverage m/definition/주담
    url: https://www.lexico.com/definition/주담
  - name: Lexico GSC Coverage m/synonyms/pyridine_base
    url: https://www.lexico.com/synonyms/pyridine_base
  - name: Lexico GSC Coverage m/definition/수시 납치
    url: https://www.lexico.com/definition/수시 납치
  - name: Lexico GSC Coverage m/definition/西风带
    url: https://www.lexico.com/definition/西风带
  - name: Lexico GSC Coverage m/definition/spoiliation
    url: https://www.lexico.com/definition/spoiliation
  - name: Lexico GSC Coverage m/definition/小事件
    url: https://www.lexico.com/definition/小事件
  - name: Lexico GSC Coverage m/search?utf8
    url: https://www.lexico.com/search?utf8
  - name: Lexico GSC Coverage m/en/explore/us_sample_academic_CV.pdf
    url: https://www.lexico.com/en/explore/us_sample_academic_CV.pdf
  - name: Lexico GSC Coverage m/en/explore/us_sample_career_transition_resume.pdf
    url: https://www.lexico.com/en/explore/us_sample_career_transition_resume.pdf
  - name: Lexico GSC Coverage m/synonym/down_to_earth
    url: https://www.lexico.com/synonym/down_to_earth
  - name: Lexico GSC Coverage m/en/explore/us_sample_entry-level_resume.pdf
    url: https://www.lexico.com/en/explore/us_sample_entry-level_resume.pdf
  - name: Lexico GSC Coverage m/synonyms/prepuberally
    url: https://www.lexico.com/synonyms/prepuberally
  - name: Lexico GSC Coverage m/en/definition/phobia%
    url: https://www.lexico.com/en/definition/phobia%
  - name: Lexico GSC Coverage m/en/definition/%s
    url: https://www.lexico.com/en/definition/%s
  - name: Lexico GSC Coverage m/synonyms/narrow-heartedness
    url: https://www.lexico.com/synonyms/narrow-heartedness
  - name: Lexico GSC Coverage m/en/definition/specific rotation
    url: https://www.lexico.com/en/definition/specific rotation
  - name: Lexico GSC Coverage m/definition/kennelly_layer?s=t
    url: https://www.lexico.com/definition/kennelly_layer?s=t
  - name: Lexico GSC Coverage m/definition/foot_valve?s=t
    url: https://www.lexico.com/definition/foot_valve?s=t
  - name: Lexico GSC Coverage m/en/definition/Ab integro
    url: https://www.lexico.com/en/definition/Ab integro
  - name: Lexico GSC Coverage m/synonyms/protestatory
    url: https://www.lexico.com/synonyms/protestatory
  - name: Lexico GSC Coverage m/synonyms/mummy-like
    url: https://www.lexico.com/synonyms/mummy-like
  - name: Lexico GSC Coverage m/synonyms/microlight
    url: https://www.lexico.com/synonyms/microlight
  - name: Lexico GSC Coverage m/synonyms/aksumite
    url: https://www.lexico.com/synonyms/aksumite
  - name: Lexico GSC Coverage m/synonyms/oarage
    url: https://www.lexico.com/synonyms/oarage
  - name: Lexico GSC Coverage m/synonyms/ins
    url: https://www.lexico.com/synonyms/ins
  - name: Lexico GSC Coverage m/definition/as+thick+as+two%2
    url: https://www.lexico.com/definition/as+thick+as+two%2
  - name: Lexico GSC Coverage m/definition/caf%c
    url: https://www.lexico.com/definition/caf%c
  - name: Lexico GSC Coverage m/definition/webtoonhttp:/gadgetplus.id/line-webtoon-x-popcon-asia/2016.http:/science.nas.nasa.gov/Pubs/TechReports/NASreports/NAS-98-014http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-digital-bagi-pecinta-komikhttp:/www.kompasiana.com/rikkai/webtoon-dan-kualitaskomentar-remaja- 
    url: https://www.lexico.com/definition/webtoonhttp:/gadgetplus.id/line-webtoon-x-popcon-asia/2016.http:/science.nas.nasa.gov/Pubs/TechReports/NASreports/NAS-98-014http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-http:/www.antaranews.com/berita/495706/line-hadirkan-webtoon-platform-digital-bagi-pecinta-komikhttp:/www.kompasiana.com/rikkai/webtoon-dan-kualitaskomentar-remaja- 
  - name: Lexico GSC Coverage m/definition/art [06
    url: https://www.lexico.com/definition/art [06
  - name: Lexico GSC Coverage m/definition/city [06
    url: https://www.lexico.com/definition/city [06
  - name: Lexico GSC Coverage m/en/definition/public assistance
    url: https://www.lexico.com/en/definition/public assistance
  - name: Lexico GSC Coverage m/definition/potential [accessed 17/10/2016
    url: https://www.lexico.com/definition/potential [accessed 17/10/2016
  - name: Lexico GSC Coverage m/definition/重庆yabo亚搏预测号码【┃总代2⒏7⒏01705[ｑ]】】
    url: https://www.lexico.com/definition/重庆yabo亚搏预测号码【┃总代2⒏7⒏01705[ｑ]】】
  - name: Lexico GSC Coverage m/definition/substitute [150328
    url: https://www.lexico.com/definition/substitute [150328
  - name: Lexico GSC Coverage m/definition/curlicues
    url: https://www.lexico.com/definition/curlicues
  - name: Lexico GSC Coverage m/definition/scanner driver
    url: https://www.lexico.com/definition/scanner driver
  - name: Lexico GSC Coverage m/definition/grigri
    url: https://www.lexico.com/definition/grigri
  - name: Lexico GSC Coverage m/search?filter=en_dictionary&query=what_do_you_know_about_that
    url: https://www.lexico.com/search?filter=en_dictionary&query=what_do_you_know_about_that
  - name: Lexico GSC Coverage m/definition/frame-driven
    url: https://www.lexico.com/definition/frame-driven
  - name: Lexico GSC Coverage m/definition/curity
    url: https://www.lexico.com/definition/curity
  - name: Lexico GSC Coverage m/definition/pendentives
    url: https://www.lexico.com/definition/pendentives
  - name: Lexico GSC Coverage m/definition/chopper spectrometer
    url: https://www.lexico.com/definition/chopper spectrometer
  - name: Lexico GSC Coverage m/definition/枹木履
    url: https://www.lexico.com/definition/枹木履
  - name: Lexico GSC Coverage om/definition/awar
    url: "https://www.lexico.com/definition/awar[broken reference: aware__2]"
  - name: Lexico GSC Coverage m/en/definition/peracarid_[adjective]
    url: https://www.lexico.com/en/definition/peracarid_[adjective]
  - name: Lexico GSC Coverage m/en/definition/subsidiarity]
    url: https://www.lexico.com/en/definition/subsidiarity]

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Lexico Uptime Monitor
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
